# ----------------------------------------
# Lua code format check
#
# Using "Stylua" action
# https://github.com/marketplace/actions/stylua
# ----------------------------------------

name: 'Scheduled stale check'
on:
  schedule:
    - cron: "0 3 * * *" # at 03:00:00 ever day

permissions:
  contents: write # only for delete-branch option
  issues: write
  pull-requests: write

jobs:
  stale:
    runs-on: ubuntu-latest
    steps:
      - run: echo "ğŸš€ Job automatically triggered by ${{ github.event_name }}"
      - run: echo "ğŸ§ Job running on ${{ runner.os }} server"
      - run: echo "ğŸ™ Using ${{ github.ref }} branch from ${{ github.repository }} repository"

      - uses: actions/checkout@v4
      - run: echo "ğŸ™ Checkout of ${{ github.repository }} repository to the CI runner."

      - uses: JohnnyMorganz/stylua-action@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          version: latest # NOTE: we recommend pinning to a specific version in case of formatting changes
          # CLI arguments
          args: --check .

      # Summary
      - run: echo "ğŸ¨ Lua code format checked with stylua-action
      - run: echo "ğŸ Job status is ${{ job.status }}."
